'use client'

import { Download, FileText } from 'lucide-react'
import { Badge } from '@/components/ui/Badge'

interface Invoice {
  id: string
  stripe_invoice_id: string | null
  amount_paid: number | null
  currency: string
  period_start: string | null
  period_end: string | null
  status: string | null
  paid_at: string | null
  created_at: string
}

interface InvoiceHistoryProps {
  invoices: Invoice[]
}

const statusColors: Record<string, string> = {
  paid: 'bg-emerald-100 text-emerald-700',
  draft: 'bg-slate-100 text-slate-700',
  open: 'bg-amber-100 text-amber-700',
  void: 'bg-slate-100 text-slate-700',
  uncollectible: 'bg-rose-100 text-rose-700',
}

export function InvoiceHistory({ invoices }: InvoiceHistoryProps) {
  if (invoices.length === 0) {
    return (
      <div className="rounded-2xl border-2 border-dashed border-slate-200 p-12 text-center">
        <FileText size={32} className="mx-auto text-slate-300 mb-3" />
        <p className="text-slate-500 font-medium">No invoices yet</p>
        <p className="text-sm text-slate-400 mt-1">Your invoices will appear here once you have an active subscription.</p>
      </div>
    )
  }

  return (
    <div className="space-y-4">
      <div className="overflow-x-auto rounded-2xl border border-slate-200">
        <table className="w-full text-sm">
          <thead className="bg-slate-50 border-b border-slate-200">
            <tr>
              <th className="text-left py-3 px-4 font-medium text-slate-700">Date</th>
              <th className="text-left py-3 px-4 font-medium text-slate-700">Period</th>
              <th className="text-right py-3 px-4 font-medium text-slate-700">Amount</th>
              <th className="text-left py-3 px-4 font-medium text-slate-700">Status</th>
              <th className="text-center py-3 px-4 font-medium text-slate-700">Action</th>
            </tr>
          </thead>
          <tbody>
            {invoices.map((invoice) => (
              <tr key={invoice.id} className="border-b border-slate-100 hover:bg-slate-50">
                <td className="py-3 px-4 text-slate-900 font-medium">
                  {new Date(invoice.created_at).toLocaleDateString()}
                </td>
                <td className="py-3 px-4 text-slate-600 text-xs">
                  {invoice.period_start && invoice.period_end ? (
                    <>
                      {new Date(invoice.period_start).toLocaleDateString()} -{' '}
                      {new Date(invoice.period_end).toLocaleDateString()}
                    </>
                  ) : (
                    '—'
                  )}
                </td>
                <td className="py-3 px-4 text-right">
                  <span className="font-semibold text-slate-900">
                    {invoice.amount_paid
                      ? `$${(invoice.amount_paid / 100).toFixed(2)}`
                      : '—'}
                  </span>
                </td>
                <td className="py-3 px-4">
                  <Badge className={statusColors[invoice.status || 'draft'] || 'bg-slate-100 text-slate-700'}>
                    {(invoice.status || 'draft').charAt(0).toUpperCase() + (invoice.status || 'draft').slice(1)}
                  </Badge>
                </td>
                <td className="py-3 px-4 text-center">
                  {invoice.stripe_invoice_id ? (
                    <a
                      href={`https://invoice.stripe.com/i/${invoice.stripe_invoice_id}`}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="inline-flex items-center gap-1 text-indigo-600 hover:text-indigo-700 font-medium"
                    >
                      <Download size={14} /> PDF
                    </a>
                  ) : (
                    <span className="text-slate-400 text-xs">—</span>
                  )}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      <p className="text-xs text-slate-500">
        Invoices are automatically generated by Stripe. <a href="https://support.stripe.com" target="_blank" rel="noopener noreferrer" className="text-indigo-600 hover:underline">Learn more</a>
      </p>
    </div>
  )
}
