'use server'

// Server actions for the Construction Plans module. Mutations run under the
// CALLER's session so RLS is the permission system (managers upload/manage,
// admins delete — same gates as the migration's policies). The admin client
// is used only where storage objects must be removed.

import { revalidatePath } from 'next/cache'
import { createClient } from '@/lib/supabase/server'
import { createAdminClient } from '@/lib/supabase/admin'
import { logger } from '@/lib/logger'
import type { MarkupElement, PlanSetType } from '@/types/plans'

type Result<T = undefined> = { success: true; data?: T } | { success: false; error: string }

async function requireUser() {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) throw new Error('Not authenticated')
  const { data: profile } = await supabase
    .from('profiles').select('company_id, role, full_name').eq('id', user.id).single()
  if (!profile?.company_id) throw new Error('No organization')
  return { supabase, user, profile }
}

function fail(err: unknown, context: string): { success: false; error: string } {
  logger.error(context, err)
  return { success: false, error: err instanceof Error ? err.message : 'Something went wrong' }
}

// ─── Import ──────────────────────────────────────────────────────────────────

export interface ImportSheetInput {
  sheetNumber: string
  title: string
  discipline: string
  revisionLabel: string
  revisionDate: string | null
  pdfPath: string          // already uploaded by the browser
  thumbPath: string | null
  pageWidth: number
  pageHeight: number
  fileSize: number
  extractedText: string
  sourceFileName: string
  sourcePageNumber: number
  /** Pre-generated by the client so storage paths and rows agree. */
  sheetId: string
  revisionId: string
  /** When revising an existing sheet, its id (client matched by number). */
  existingSheetId: string | null
}

export async function commitPlanImport(
  projectId: string,
  setInfo: { existingSetId: string | null; name: string; setType: PlanSetType; issueDate: string | null },
  sheets: ImportSheetInput[],
): Promise<Result<{ imported: number; revised: number }>> {
  try {
    const { supabase, user, profile } = await requireUser()
    if (sheets.length === 0) return { success: false, error: 'No sheets to import' }

    // Resolve the drawing set
    let setId = setInfo.existingSetId
    if (!setId) {
      const { data: set, error } = await supabase.from('plan_sets').insert({
        company_id: profile.company_id,
        project_id: projectId,
        name: setInfo.name,
        set_type: setInfo.setType,
        issue_date: setInfo.issueDate,
        created_by: user.id,
      }).select('id').single()
      if (error) throw new Error(error.message)
      setId = set.id
    }

    let imported = 0
    let revised = 0
    const revisedNumbers: string[] = []

    // Base sort order after existing sheets
    const { data: maxRow } = await supabase
      .from('plan_sheets').select('sort_order').eq('project_id', projectId)
      .order('sort_order', { ascending: false }).limit(1).maybeSingle()
    let nextOrder = (maxRow?.sort_order ?? 0) + 1

    for (const s of sheets) {
      if (s.existingSheetId) {
        // New revision of an existing sheet: supersede the old current
        const { error: revErr } = await supabase.from('plan_revisions').insert({
          id: s.revisionId,
          company_id: profile.company_id,
          sheet_id: s.existingSheetId,
          revision_label: s.revisionLabel,
          revision_date: s.revisionDate,
          status: 'current',
          pdf_path: s.pdfPath,
          thumb_path: s.thumbPath,
          page_width: s.pageWidth,
          page_height: s.pageHeight,
          file_size: s.fileSize,
          extracted_text: s.extractedText.slice(0, 20000),
          source_file_name: s.sourceFileName,
          source_page_number: s.sourcePageNumber,
          uploaded_by: user.id,
        })
        if (revErr) throw new Error(`${s.sheetNumber}: ${revErr.message}`)
        await supabase.from('plan_revisions')
          .update({ status: 'superseded' })
          .eq('sheet_id', s.existingSheetId).neq('id', s.revisionId)
        const { error: updErr } = await supabase.from('plan_sheets')
          .update({ current_revision_id: s.revisionId, title: s.title || undefined, is_archived: false })
          .eq('id', s.existingSheetId)
        if (updErr) throw new Error(`${s.sheetNumber}: ${updErr.message}`)
        revised++
        revisedNumbers.push(`${s.sheetNumber} → Rev ${s.revisionLabel}`)
      } else {
        const { error: sheetErr } = await supabase.from('plan_sheets').insert({
          id: s.sheetId,
          company_id: profile.company_id,
          project_id: projectId,
          set_id: setId,
          sheet_number: s.sheetNumber,
          title: s.title,
          discipline: s.discipline,
          sort_order: nextOrder++,
        })
        if (sheetErr) {
          if (/duplicate|unique/i.test(sheetErr.message)) {
            throw new Error(`Sheet ${s.sheetNumber} already exists in this project. Re-run the import — it will be offered as a revision.`)
          }
          throw new Error(`${s.sheetNumber}: ${sheetErr.message}`)
        }
        const { error: revErr } = await supabase.from('plan_revisions').insert({
          id: s.revisionId,
          company_id: profile.company_id,
          sheet_id: s.sheetId,
          revision_label: s.revisionLabel,
          revision_date: s.revisionDate,
          status: 'current',
          pdf_path: s.pdfPath,
          thumb_path: s.thumbPath,
          page_width: s.pageWidth,
          page_height: s.pageHeight,
          file_size: s.fileSize,
          extracted_text: s.extractedText.slice(0, 20000),
          source_file_name: s.sourceFileName,
          source_page_number: s.sourcePageNumber,
          uploaded_by: user.id,
        })
        if (revErr) throw new Error(`${s.sheetNumber}: ${revErr.message}`)
        await supabase.from('plan_sheets').update({ current_revision_id: s.revisionId }).eq('id', s.sheetId)
        imported++
      }
    }

    await supabase.from('plan_activity').insert({
      company_id: profile.company_id,
      project_id: projectId,
      actor_id: user.id,
      action: revised > 0 && imported === 0 ? 'revised' : 'uploaded',
      detail: {
        set_name: setInfo.name,
        added: imported,
        revised,
        revised_sheets: revisedNumbers.slice(0, 20),
        source: sheets[0]?.sourceFileName,
      },
    })

    revalidatePath(`/app/projects/${projectId}/plans`)
    return { success: true, data: { imported, revised } }
  } catch (err) {
    return fail(err, 'commitPlanImport')
  }
}

// ─── Sheet management ────────────────────────────────────────────────────────

export async function updateSheetMeta(
  projectId: string,
  sheetIds: string[],
  patch: Partial<{
    title: string; discipline: string; set_id: string | null; drawing_type: string | null
    building: string | null; floor: string | null; area: string | null
    tags: string[]; is_archived: boolean; sheet_number: string
  }>,
): Promise<Result> {
  try {
    const { supabase } = await requireUser()
    const { error } = await supabase.from('plan_sheets').update(patch).in('id', sheetIds)
    if (error) throw new Error(error.message)
    revalidatePath(`/app/projects/${projectId}/plans`)
    return { success: true }
  } catch (err) {
    return fail(err, 'updateSheetMeta')
  }
}

export async function setCurrentRevision(projectId: string, sheetId: string, revisionId: string): Promise<Result> {
  try {
    const { supabase, user, profile } = await requireUser()
    const { data: rev } = await supabase.from('plan_revisions')
      .select('id, sheet_id, revision_label').eq('id', revisionId).single()
    if (!rev || rev.sheet_id !== sheetId) throw new Error('Revision not found')
    await supabase.from('plan_revisions').update({ status: 'superseded' }).eq('sheet_id', sheetId)
    await supabase.from('plan_revisions').update({ status: 'current' }).eq('id', revisionId)
    const { error } = await supabase.from('plan_sheets').update({ current_revision_id: revisionId }).eq('id', sheetId)
    if (error) throw new Error(error.message)
    await supabase.from('plan_activity').insert({
      company_id: profile.company_id, project_id: projectId, actor_id: user.id,
      action: 'superseded', detail: { sheet_id: sheetId, made_current: rev.revision_label },
    })
    revalidatePath(`/app/projects/${projectId}/plans`)
    return { success: true }
  } catch (err) {
    return fail(err, 'setCurrentRevision')
  }
}

export async function deleteSheets(projectId: string, sheetIds: string[]): Promise<Result> {
  try {
    const { supabase, user, profile } = await requireUser()
    if (!['owner', 'admin'].includes(profile.role)) throw new Error('Only admins can delete drawings')
    const admin = createAdminClient()

    const { data: sheets } = await supabase.from('plan_sheets')
      .select('id, sheet_number').in('id', sheetIds).eq('project_id', projectId)
    if (!sheets?.length) return { success: true }

    // Remove storage objects for every revision of every sheet
    const { data: revs } = await supabase.from('plan_revisions')
      .select('pdf_path, thumb_path').in('sheet_id', sheetIds)
    const paths = (revs ?? []).flatMap((r) => [r.pdf_path, r.thumb_path]).filter(Boolean) as string[]
    if (paths.length) {
      const { error: rmErr } = await admin.storage.from('project-attachments').remove(paths)
      if (rmErr) logger.warn('deleteSheets: storage cleanup incomplete', { rmErr })
    }

    const { error } = await supabase.from('plan_sheets').delete().in('id', sheetIds)
    if (error) throw new Error(error.message)

    await supabase.from('plan_activity').insert({
      company_id: profile.company_id, project_id: projectId, actor_id: user.id,
      action: 'deleted', detail: { sheets: sheets.map((s) => s.sheet_number).slice(0, 30) },
    })
    revalidatePath(`/app/projects/${projectId}/plans`)
    return { success: true }
  } catch (err) {
    return fail(err, 'deleteSheets')
  }
}

// ─── Markups ─────────────────────────────────────────────────────────────────

export async function saveMarkup(
  revisionId: string,
  scope: 'personal' | 'project',
  elements: MarkupElement[],
): Promise<Result> {
  try {
    const { supabase, user, profile } = await requireUser()
    if (scope === 'project' && !['owner', 'admin', 'manager'].includes(profile.role)) {
      throw new Error('Only managers can edit project markups')
    }
    const { error } = await supabase.from('plan_markups').upsert({
      company_id: profile.company_id,
      revision_id: revisionId,
      scope,
      user_id: user.id,
      elements,
      updated_at: new Date().toISOString(),
    }, { onConflict: 'revision_id,scope,user_id' })
    if (error) throw new Error(error.message)
    return { success: true }
  } catch (err) {
    return fail(err, 'saveMarkup')
  }
}

// ─── Pins ────────────────────────────────────────────────────────────────────

export async function createPin(input: {
  sheetId: string; revisionId: string | null; x: number; y: number
  note: string; assignedTo: string | null; dueDate: string | null
}): Promise<Result<{ id: string }>> {
  try {
    const { supabase, user, profile } = await requireUser()
    const { data, error } = await supabase.from('plan_pins').insert({
      company_id: profile.company_id,
      sheet_id: input.sheetId,
      revision_id: input.revisionId,
      x: input.x, y: input.y,
      note: input.note,
      assigned_to: input.assignedTo,
      due_date: input.dueDate,
      created_by: user.id,
    }).select('id').single()
    if (error) throw new Error(error.message)
    return { success: true, data: { id: data.id } }
  } catch (err) {
    return fail(err, 'createPin')
  }
}

export async function addPinComment(pinId: string, body: string): Promise<Result> {
  try {
    const { supabase, user, profile } = await requireUser()
    const { error } = await supabase.from('plan_pin_comments').insert({
      company_id: profile.company_id, pin_id: pinId, author_id: user.id, body,
    })
    if (error) throw new Error(error.message)
    return { success: true }
  } catch (err) {
    return fail(err, 'addPinComment')
  }
}

export async function setPinStatus(pinId: string, status: 'open' | 'resolved'): Promise<Result> {
  try {
    const { supabase, user } = await requireUser()
    const { error } = await supabase.from('plan_pins').update(
      status === 'resolved'
        ? { status, resolved_by: user.id, resolved_at: new Date().toISOString() }
        : { status, resolved_by: null, resolved_at: null },
    ).eq('id', pinId)
    if (error) throw new Error(error.message)
    return { success: true }
  } catch (err) {
    return fail(err, 'setPinStatus')
  }
}

export async function deletePin(pinId: string): Promise<Result> {
  try {
    const { supabase } = await requireUser()
    const { error } = await supabase.from('plan_pins').delete().eq('id', pinId)
    if (error) throw new Error(error.message)
    return { success: true }
  } catch (err) {
    return fail(err, 'deletePin')
  }
}

// ─── Activity log for downloads (meaningful events only: sets, not sheets) ──

export async function logPlanDownload(projectId: string, detail: { kind: string; count: number; label?: string }): Promise<Result> {
  try {
    const { supabase, user, profile } = await requireUser()
    // Single-sheet downloads are routine, not activity-worthy noise.
    if (detail.count < 2) return { success: true }
    await supabase.from('plan_activity').insert({
      company_id: profile.company_id, project_id: projectId, actor_id: user.id,
      action: 'downloaded', detail,
    })
    return { success: true }
  } catch (err) {
    return fail(err, 'logPlanDownload')
  }
}

// ─── Calibration ─────────────────────────────────────────────────────────────

export async function saveCalibration(
  revisionId: string,
  calibration: { pointsPerUnit: number; unit: 'ft' | 'm' } | null,
): Promise<Result> {
  try {
    const { supabase } = await requireUser()
    const { error } = await supabase.from('plan_revisions')
      .update({ scale_calibration: calibration }).eq('id', revisionId)
    if (error) throw new Error(error.message)
    return { success: true }
  } catch (err) {
    return fail(err, 'saveCalibration')
  }
}
